name: create integeration input
description: create integration input with azure input for apps via kubernetes
inputs:
  applications:
    description: a comma separated list of all applications (at least one) which azure input is to be created for
    required: true
outputs:
  integration_input_path:
    description: the path to where secrets from azure applications have been stored
runs:
  using: node12
  main: dist/index.js
