name: Cucumber Reports
description: Links cucumber reports to given path for a github page (index.md) in docs folder (folder for github pages)
inputs:
  pages_address:
    description: https://<organisasjon>.github.io/<prosjekt> (web adresse til github pages for organisasjon/prosjekt
    required: true
  path_github_page:
    description: full filsti til markdown-fil som skal ha linker til utførte cucumber rapporter
    required: true
runs:
  using: node12
  main: dist/index.js
