name: link-pages
description: lager linker av alle oppgitte siderfor visning på github pages
inputs:
  folder_link_pages:
    description: mappe som inneholder alle filer som skal vises på gh-pages
    required: true
  path_page:
    description: full filsti til markdown-fil som skal ha linker til andre filer
    required: true
  pattern:
    description: pattern (*.filtype) som skal brukes for å finne filene som skal linkes
    required: true
runs:
  using: node12
  main: dist/index.js
