name: Clone cucumber and nais-app
description: Clones a github project end and will also clone a github project (nais application) to be able to read the configuration
runs:
  using: node12
  main: dist/index.js
inputs:
  cucumber_project:
    description: "The name of the github cucumber-project, ie: https://github.com/navikt/<cucumber_project>"
    required: true
    default: bidrag-cucumber-backend
  folder_nais_apps:
    description: The name of the folder where the nais-application will be cloned so tests can access nais configuration
    required: true
    default: apps
  extra_clones:
    description: delimiter-separated list with project to be cloned alongside the nais-application beeing tested, ex <testdata-app-a><delimiter-character><testdata-app-b>
    required: false
  delimiter:
    description: delimiter-character to use if extra clones is to be cloned
    required: true
    default: ;
